import type { Metadata } from "next";
import "./globals.css";

import StyledComponentsRegistry from "@/lib/registry";
import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "../services/queryClient";
import { AuthProvider } from "@/context/authContext";

export const metadata: Metadata = {
  title: "Boné Simões",
  description: "Generated by create next app",
  icons: {
    icon: "https://res.cloudinary.com/dz46wt0iy/image/upload/fl_preserve_transparency/v1769912818/1769912016331_ox3dlk.jpg?_s=public-apps",
    shortcut: "https://res.cloudinary.com/dz46wt0iy/image/upload/fl_preserve_transparency/v1769912818/1769912016331_ox3dlk.jpg?_s=public-apps",
    apple: "https://res.cloudinary.com/dz46wt0iy/image/upload/fl_preserve_transparency/v1769912818/1769912016331_ox3dlk.jpg?_s=public-apps",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <QueryClientProvider client={queryClient}>
          <AuthProvider>
            <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
